#apiVersion: v1
#kind: Service
#metadata:
  #name: netflix-app
  #labels:
    #app: netflix-app
#spec:
  #type: NodePort
  #ports:
  #- port: 80
    #targetPort: 80
    #nodePort: 30007
  #selector:
    #app: netflix-app
apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  namespace: default
spec:
  selector:
    app: netflix-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 80
    port: 30007
